source 'https://rubygems.org'

gem 'rake'
gem 'sequel'
gem 'mysql2'

gem 'grape'
gem 'grape-entity'
gem 'grape-swagger'
gem 'rack-cors'
gem 'dotenv'
gem 'puma'


group :test do
  gem 'database_cleaner'
end

group :development, :test do
  gem 'byebug'
  gem 'cane'
  gem 'rubocop'
end
